---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: blueprint
description: The next-generation Fedora-based workstation — built for the Framework Desktop with AMD Ryzen™ 9 395 Max+ with 128GB RAM
base-image: ghcr.io/ublue-os/base-main
image-version: 42

modules:
  - from-file: base.yml
  - from-file: copr.yml
  - from-file: quickshell.yml

  - type: dnf
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - virtualbox-guest-additions
        - toolbox
        - nvtop
        - sway
        - yggdrasil
        - adcli 
        - libdnf-plugin-subscription-manager 
        - python3-subscription-manager-rhsm 
        - subscription-manager 
        - subscription-manager-rhsm-certificates 

  - type: kargs
    kargs:
      - amd_iommu=off
      - amdttm.pages_limit=27648000
      - amdttm.page_pool_size=13824000
# - amdgpu.gttsize=131072     → 128 GiB unified memory (131072 MiB)
# - ttm.pages_limit=33554432  → 128 GiB pinned memory (33554432 × 4 KiB)

  - type: files
    files:
      - source: system
        destination: /

  - from-file: fonts.yml

  - type: systemd
    system:
      enabled:
        - sddm-boot.service
        - enable-linger.service
        - autologin.service
        - tailscaled.service
        - systemd-resolved.service
      disabled: []

  - type: chezmoi
    repository: "https://github.com/mecattaf/dotfiles"
    run-every: '1d'
    wait-after-boot: '5m'
    disable-init: false
    disable-update: false

  - type: brew
    nofile-limits: true
    brew-analytics: false

  - type: justfiles
    include:
        - setup.just

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: user
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
        install:
          - com.google.Chrome
          - it.mijorus.gearlever
          - com.hunterwittenborn.Celeste
          - it.mijorus.collector
          - com.obsproject.Studio
          - com.obsproject.Studio.Plugin.OBSVkCapture
          - org.gnome.Lollypop
          - org.mozilla.firefox
          # - org.freedesktop.Platform.VulkanLayer.OBSVkCapture
          # - org.freedesktop.Platform.GStreamer.gstreamer-vaapi

  - type: signing
